version: '3.8'

networks:
  tools:

services:
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    networks:
      - tools
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ./data/redisdata:/data
    restart: on-failure

  redismodules:
    image: redislabs/redismod:latest
    ports:
      - 6380:6379
    networks:
      - tools
    volumes:
      - ./data/redismoddata:/data
    environment:
      - TZ=Asia/Dhaka
    restart: on-failure

  redisinsights:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    networks:
      - tools
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ./data/redisinsightdata:/db

  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    networks:
      - tools
    volumes:
      - ./data/mongodata:/data/db
    restart: on-failure
    environment:
      - TZ=Asia/Dhaka

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - tools
    volumes:
      - ./data/postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Dhaka

  mysql:
    image: mysql
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    networks:
      - tools
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=tools
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - TZ=Asia/Dhaka

